---
title: promise详解
date: 2018-11-07 00:31:30
tags: [js]
categories: [js]
---

js中所有的代码都是单线程执行的，但是有写操作，必须异步执行，比如：ajax；异步执行的结果回调可以使用回调函数实现；如何优雅的完成这个操作呢 ？promise。

## 定义
承诺将来会执行的代码（回调），这个对象叫做Promise对象。

```
setTimeout(cb1, 1000);

function cb1() {
	console.log('1s之后执行');
}
xxxx

```

如何优雅的写这个异步逻辑呢 ？

```

fa = new Promise((res,rej) => {
	res('异步返回结果');
})


fa.then((res) => {
	console.log(res);
})
console.log('事件流');

```

上述可以看到，'事件流'优先被打印，异步操作fa的回调在事件的栈中，在事件流之后执行。

## 参数详解

Promise对象有两个参数：resolve，reject  分别用来保存异步成功的结果，和失败的结果。

```
console.log('1. 事件流开始');

let fa = new Promise((resolve, reject) => {
	
	setTimeout(function(){
		console.log('4. promise中异步执行');
		let randomX = Math.random() * 10;
		console.log(randomX);
		if (randomX > 5) {
			resolve('5. 异步返回正确结果');
		} else {
			reject('5. 异步返回错误结果');
		}
	}, 1000); 
	console.log('2. promise中同步执行');
	
});

// fa.then((resSuc) => {
//     console.log(resSuc);
//     console.log('6. promise回调结束')
// }, (resFail) => {
//     console.log(resFail);
//     console.log('6. promise回调结束')
// })

// 或者使用catch方法代替第二个回调
fa.then((resSuc) => {
	console.log(resSuc);
	console.log('6. promise回调结束')
}).catch( (resFail)=> {
	console.log(resFail);
	console.log('6. promise回调结束')
})

console.log('3. 事件流其他事件');
```

Promise的回调接受两个参数，一个是resolve对应的成功回调，参数是Promise对象返回的成功值；一个是reject对应的失败回调，参数是Promise对象返回的错误值；

## 串行多个任务

```
console.log('事件流开始');
        
        function fa1(num){
            return new Promise((resolve, reject) => {
                setTimeout(function(){
                    let randomX = Math.random() * 10;
                    console.log('fa1随机数：' + randomX);
                    if (randomX > 5) {
                        resolve(num + 1000);
                    } else {
                        reject('fa1返回错误结果');
                    }
                }, 1000); 
            console.log('fa1中同步执行');
            })
        }
        function fa2(num){
            return new Promise((resolve, reject) => {
                setTimeout(function(){
                    let randomX = Math.random() * 10;
                    console.log('fa2随机数：' + randomX);
                    if (randomX > 5) {
                        resolve(num + 10000);
                    } else {
                        reject('fa2返回错误结果');
                    }
                }, 1000); 
            console.log('fa2中同步执行');
            })
        }
        let fa = new Promise((resolve, reject) => {
            setTimeout(function(){
                let randomX = Math.random() * 10;
                console.log(randomX);
                if (randomX > 5) {
                    resolve(100);
                } else {
                    reject('fa返回错误结果');
                }
            }, 1000); 
            console.log('fa中同步执行');
            
        });

        fa.then(fa1).then(fa2).then((resSuc) => {
            console.log(resSuc);
            console.log('回调结束')
        }, (resFail) => {
            console.log(resFail);
            console.log('回调结束')
        })

        

        console.log('事件流其他事件');
```

每一个任务都是一个promise对象，每一个任务会把自己的resolve结果传递给下一个任务，直到任务结束，回调结束；如果中间某一个任务发生reject，那么执行最后的错误回调，不再执行之后的任务，回调结束。

## 并行执行多个任务（all）

```
console.log('事件流开始');

let fa1 = new Promise((resolve, reject) => {
	setTimeout(function(){
		let randomX = Math.random() * 10;
		console.log('fa1随机数：' + randomX);
		if (randomX > 5) {
			resolve(randomX + 1000);
		} else {
			reject('fa1返回错误结果');
		}
	}, 1000); 
	console.log('fa1中同步执行');
})
let fa2 = new Promise((resolve, reject) => {
	setTimeout(function(){
		let randomX = Math.random() * 10;
		console.log('fa2随机数：' + randomX);
		if (randomX > 5) {
			resolve(randomX + 10000);
		} else {
			reject('fa2返回错误结果');
		}
	}, 1000); 
	console.log('fa2中同步执行');
})

Promise.all([fa1, fa2]).then((resSuc) => {
	console.log(resSuc);
	console.log('回调结束')
}, (resFail) => {
	console.log(resFail);
	console.log('回调结束')
})



console.log('事件流其他事件');
```

1. Promise.all()等待所有异步操作结果返回了，才会继续执行；
2. Promise.race()其中任意一个异步操作结果返回了，就会继续执行；

## 总结

1 . promise的优点

    1. 状态维护，结果不变性，过程独立性。
    2. 链式操作，写法优雅美观。

2 . promise的缺点

    1. 吞没错误。由于promise对象完全接管了异步操作，且过程不可见只返回结果，对异常信息的处理返回要求比较高。
    2. 无法取消。
    3. 过程无法中断。

3 . 尝试的优化：如何取消已经开始的promise

    1. 异步内部处理，抛出异常补货，中断promise链。
    2. 结合业务场景，结合race等方法使用。